#!/bin/bash
#
#
####################################################################################
# script meteo che usa  oopenweathermap per i dati e li riporta a terminale      
#
# v:1.4                                                                    
#
# dipendenze: curl,jq,cat,bc
#
#
####################################################################################



# set api-key

key_meteo="1487dd8a93bfd85d278d9ac8dcfee94c"



# set global variable

surc_city=$1
api1="http://api.openweathermap.org/data/2.5/find?q="
api_par="&units=metric&appid="
api_lang="&lang=en"
api2="http://api.openweathermap.org/data/2.5/forecast/daily?id="
api3="http://api.openweathermap.org/data/2.5/forecast?id="





# get jason weather data now and extract city id

rm meteonow.txt
echo " "
echo "get data: weather now... "
curl -s $api1$surc_city$api_par$key_meteo$api_lang > meteonow.txt
echo " "
city_id=`cat meteonow.txt | jq '.list[0]|.id'`



# get jason weather data forecast general 5 day

rm meteo5.txt
echo " "
echo "get data: forecast 5 day..."
echo " "
curl -s $api2$city_id$api_par$key_meteo > meteo5.txt

echo " "
echo "extract data file... "
echo " "
echo " "
echo " "

# dopo 5 secondi pulisco schermo
sleep 5
echo -e '\0033\0143'


# exstract data to jason file

city_name=`cat meteonow.txt | jq -r '.list[0]|.name'`
L=`cat meteonow.txt | jq -r '.list[0]|.sys[]'`
Lat=`cat meteonow.txt | jq -r '.list[0]|.coord.lat'`
Lon=`cat meteonow.txt | jq -r '.list[0]|.coord.lon'`
data_X=`cat meteonow.txt | jq -r '.list[0]|.dt'`
data_U=`date  -d @$data_X`
Wcond_n=`cat meteonow.txt | jq -r '.list[0]|.weather[].main'`
Wcond_nd=`cat meteonow.txt | jq -r '.list[0]|.weather[].description'`
T=`cat meteonow.txt | jq -r '.list[0]|.main.temp'`
Tmax=`cat meteonow.txt | jq -r '.list[0]|.main.temp_max'`
Tmin=`cat meteonow.txt | jq -r '.list[0]|.main.temp_min'`
Hm=`cat meteonow.txt | jq -r '.list[0]|.main.humidity'`
PrS=`cat meteonow.txt | jq -r '.list[0]|.main.pressure'`
ClD=`cat meteonow.txt | jq -r '.list[0]|.clouds[]'`
R=`cat meteonow.txt | jq -r '.list[0]|.rain'`
S=`cat meteonow.txt | jq -r '.list[0]|.snow'`
Ws=`cat meteonow.txt | jq -r '.list[0]|.wind.speed'`
Wsd=`cat meteonow.txt | jq -r '.list[0]|.wind.deg'`


# convert m/s to Km/s 
WsKM=$(echo "3.6"*$Ws | bc)


# convert degreese to cardinal name

if (($(echo "$Wsd>= 0" | bc))); then W_nc="N"; fi;

if (($(echo "$Wsd>= 11.25" | bc))); then W_nc="N-NE"; fi;

if (($(echo "$Wsd>= 33.25" | bc))); then W_nc="NE"; fi;

if (($(echo "$Wsd>= 56.25" | bc))); then W_nc="E-NE"; fi;

if (($(echo "$Wsd>= 78.75" | bc))); then W_nc="E"; fi;

if (($(echo "$Wsd>= 101.25" | bc))); then W_nc="E-SE"; fi;

if (($(echo "$Wsd>= 123.75" | bc))); then W_nc="SE"; fi;

if (($(echo "$Wsd>= 146.25" | bc))); then W_nc="S-SE"; fi;

if (($(echo "$Wsd>= 168.75" | bc))); then W_nc="S"; fi;

if (($(echo "$Wsd>= 191.25" | bc))); then W_nc="S-SW"; fi;

if (($(echo "$Wsd>= 213.75" | bc))); then W_nc="SW"; fi;

if (($(echo "$Wsd>= 236.25" | bc))); then W_nc="W-SW"; fi;

if (($(echo "$Wsd>= 258.75" | bc))); then W_nc="W"; fi;

if (($(echo "$Wsd>= 281.25" | bc))); then W_nc="W-NW"; fi;

if (($(echo "$Wsd>= 303.75" | bc))); then W_nc="NW"; fi;

if (($(echo "$Wsd>= 326.25" | bc))); then W_nc="N-NW"; fi;

if (($(echo "$Wsd>= 348.75" | bc))); then W_nc="N"; fi;

if (($(echo "$Wsd> 360" | bc))); then W_nc="-?-"; fi;

if (($(echo "$Wsd< 0" | bc))); then W_nc="-?-"; fi

if [ "$Wsd" = "null" ]; then W_nc="-?-"; fi;




# print to video all data..
echo " "
echo " " $city_name","$L " " "Lat: "$Lat " " "Lon: "$Lon " " "id:" $city_id
echo " " $data_U
echo " "
echo " " "Weather: "$Wcond_n"," $Wcond_nd
echo " "
echo " " "Temp (C°): "$T "  " "Tmax (C°): "$Tmax"  " "Tmin (C°): "$Tmin " " "Humidity (%): "$Hm
echo " "
echo " " "Pressure (hPa): "$PrS "  " "Clouds (%): "$ClD " " "Rain (mm): "$R " " "Snow (mm): "$S 
echo " "
echo " " "Wind speed (km/h): "$WsKM " " "Wind deg (°): "$Wsd " " "Wind dir: "$W_nc
echo " "
echo " "
